language: node_js

node_js:
    # Production
    - "4"
    # Next LTS
    - "6"
    # From the nvm docs, "this installs the latest version of node".
    - "node"

script: travis_wait npm run-script coverage

after_success: npm run-script coveralls

notifications:
  email:
    - secure: "UPDzE/JcwvnoewrGVuuVrX0TFz2Q5PYkS2xxA45FRiCPvc2KxVvC9YX0xOKklm6iiiyH95lKRgAD8D53gg1tJmpR2+Z2BAfvfyy41MDB9P5ufwn9NoulmrLFLWCQxf+fqmT1qjyle4pql44y8nN7PCejn1Zkz4pko29bz0c3Blg="
